# This is a sample aws-auth-patch.yml file.
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::915106512840:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::915106512840:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-17C402QC9VF6L
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-11T11:16:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1631"
  # uid: 86402a4e-a9ff-4721-8c24-f0c4258f7440
  uid: 3a1a8572-420c-11eb-8a51-0f60c3fc5bcb
